services:
  engine:
    image: airensoft/ovenmediaengine:latest
    container_name: stream-engine
    restart: always
    ports:
      - "1935:1935"

  web:
    image: nginx:alpine
    container_name: stream-web
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd:/etc/nginx/conf.d/htpasswd
    depends_on:
      - engine
      - backend

  # ESKİ MONITOR YERİNE ARTIK BU VAR:
  backend:
    build: ./backend
    container_name: stream-backend
    restart: always
    depends_on:
      - engine